wfw2/config/routes.rb
Rails.application.routes.draw do
  get 'products/show'
  get 'products/show_detail'
  get 'products/create'
  get 'products/modify'
  get 'products/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

wfw2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wfw2/app/models/product.rb
class Product < ApplicationRecord
end

wfw2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wfw2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  end

  def show_detail
    params.require :product_id
    @product = Product.find(params[:product_id])
  end

  def create
    if (params.has_key?(:name) && params.has_key?(:product_number) && params.has_key?(:price))
      Product.create(:name => params[:name], :product_number => params[:product_number], :price => params[:price])
      redirect_to products_show_path
    end
  end

  def modify
    params.require :product_id
    @product = Product.find(params[:product_id])

    if (params.has_key? :modify)
      @product.name = params[:name]
      @product.product_number = params[:product_number]
      @product.price = params[:price]
      @product.save
      redirect_to products_show_path
    end
  end

  def delete
    if (params.has_key? :product_id)
      product = Product.find(params[:product_id])
      if (product)
        product.destroy
      end
    else
      Product.all.each do |product|
        product.destroy
      end
    end
  end
end

wfw2/app/helpers/application_helper.rb
module ApplicationHelper
end

wfw2/app/helpers/products_helper.rb
module ProductsHelper
end

wfw2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web-Frameworks Übung 2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Produktverwaltung</h1>
    <hr />
    <%= yield %>
  </body>
</html>

wfw2/app/views/products/create.html.erb
<h2>Neues Produkt erstellen</h2>
<form>
  <input type="text" name="name" placeholder="Produktname">
  <br />
  <input type="text" name="product_number" placeholder="Produktnummer">
  <br />
  <input type="number" step="0.01" name="price" placeholder="Preis">
  <br /><br />
  <button type="submit">Erstellen</button>
</form>
<br/>
<%=link_to "Zurück zur Produktübersicht", products_show_path %>

wfw2/app/views/products/delete.html.erb
<% if (params.has_key? :product_id) %>
<h1>Produkt wurde entfernt</h1>
<% else %>
<h1>Alle Produkte wurden gelöscht</h1>
<% end %>
<br />
<%=link_to "Zurück zur Produktübersicht", products_show_path %>

wfw2/app/views/products/modify.html.erb
<h2>Produkt bearbeiten</h2>
<form>
  <input type="hidden" name="product_id" value="<%=@product.id%>"/>
  <input type="text" name="name" placeholder="Produktname" value="<%=@product.name%>">
  <br />
  <input type="text" name="product_number" placeholder="Produktnummer" value="<%=@product.product_number%>">
  <br />
  <input type="number" step="0.01" name="price" placeholder="Preis" value="<%=@product.price%>">
  <br /><br />
  <button type="submit" name="modify" value="modify">Speichern</button>
</form>
<br/>
<%=link_to "Zurück zur Produktübersicht", products_show_path %>

wfw2/app/views/products/show.html.erb
<h2>Produktübersicht</h2>
<table>
  <thead>
    <tr>
      <th>Produktname</th>
      <th>Preis</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan=3><%=link_to "Neues Produkt erstellen", products_create_path %></td>
    </tr>
    <% Product.all.each do |product| %>
    <tr>
      <td><%=product.name%></td>
      <td><%=product.price%>€</td>
      <td><%=link_to "mehr infos", products_show_detail_path({:product_id=>product.id}) %></td>
    </tr>
    <% end %>
    <tr>
      <td colspan=3><%=link_to "Alle Produkte löschen", products_delete_path %></td>
    </tr>
  </tbody>
</table>

wfw2/app/views/products/show_detail.html.erb
<h2>Detailansicht</h2>
<h3><%=@product.name%></h3>
<ul>
  <li>Produktid: <%=@product.id%></li>
  <li>Produktnummer: <%=@product.product_number%></li>
  <li>Preis: <%=@product.price%></li>
  <li><%=link_to "Bearbeiten", products_modify_path({:product_id=>@product.id}) %></li>
  <li><%=link_to "Löschen", products_delete_path({:product_id=>@product.id}) %></li>
</ul>
<a href="./show">Zurück zur Produktübersicht</a>